#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
	listen		80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
    	index		index.html index.htm index.nginx-debian.html;

    	location /redirect_me {
        	return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
}
" >/etc/nginx/sites-available/default

sudo service nginx restart
