#!/usr/bin/env bash
# Script to configure custom header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "server {
        listen          80 default_server;
        listen          [::]:80 default_server;

        root            /var/www/html;
        index           index.html index.htm index.nginx-debian.html;

	add_header X-Served-By $HOSTNAME;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
	}

	error_page 404 /404.html;
	location /404 {
        	root /var/www/html/;
        	internal;
    	}
}
" >/etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
