#!/usr/bin/env bash
# making fix short and sweet.
sudo apt update
sudo apt-get install -y net-tools

if ! sudo netstat -tulpn | grep -q :80
then
  sudo nginx -t
  sudo sed -i 's/\(listen\s*[^;]*\)\(;\)/\180\2/' /etc/nginx/nginx.conf
  sudo systemctl restart nginx
  sudo service nginx status | grep "not running"
fi
