#!/usr/bin/env bash
# Updates the system, installs net-tools, and configures nginx for port 80.

sudo apt update
sudo apt-get install -y net-tools

sudo netstat -tulpn | grep -q :80 || {
  sudo nginx -t
  sudo sed -i 's/\(listen\s*[^;]*\)\(;\)/\180\2/' /etc/nginx/nginx.conf
  sudo systemctl restart nginx
  sudo service nginx status | grep -q "not running" && echo "Nginx is not running after restart."
}
