#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements:
# -localhost resolves to 127.0.0.2
# -facebook.com resolves to 8.8.8.8.

#checks if the script is running as a root
if [[ $EUID -ne 0 ]];
then
	echo "This script must run as a root(sudo)"
	exit 1
fi
#define the host file location
hosts_file="etc/host"
#append the string to the specified file
echo "127.0.0.2 localhost" >> "$hosts_file"
echo "8.8.8.8 facebook.com" >> "$hosts_file"
#informs the user that the host file has been updated
echo "host file has been updated"
#checks if systemctl is available in the system
if command -v systemctl &> /dev/null;
then
	#restart the networking service
	systemctl restart networking
#Update the network services
        echo "Networking services have been updated"
fi
#checks again if systemctl is availble in the system
if command -v systemctl &> /dev/null;
then
	echo "Note: On Ubuntu 20.04 and later, you may need to restart the networking service manually."
fi




