#!/bin/bash

#Explaining the changes
echo "Configuring Nginx to run as nginx user and listen on port 8080.."

#Set nginx to run as the nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

#Configure Nginx to listen on all active IPs on port 8080
sed -i '/listen 80 default_server;/a \\tlisten 8080;' /etc/nginx/sites-available/default

#Restart Nginx to apply the changes
service nginx restart

echo "Nginx is now running as nginx user and listening on port 8080."
